apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
    type: myapp-nginx
spec:
  containers:
    - name: nginx-container
      image: nginx

    - name: apache2-container
      image: apache2
      
    - name: empty
      image: alpine